name: spotify_albums
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  collection: ^1.17.1
  http: ^0.13.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
